spring:
  application:
    name: matchbook

  datasource:
    url: jdbc:postgresql://localhost:5432/matchbook
    username: matchbook
    password: matchbook

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  docker:
    compose:
      enabled: false

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

    consumer:
      group-id: matchbook-matching
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.monty.matchbook.event
        spring.json.use.type.headers: false

    listener:
      concurrency: 12
      ack-mode: record

logging:
  level:
    com.monty.matchbook: DEBUG

matchbook:
  tick-size: 0.01
